@apiURL = http://localhost:4000/api/v1

###
POST {{apiURL}}/auth
Content-Type: application/json

{
  "username":"adminmanish1",
  "email": "adminmanish1@gmail.com", 
  "password": "1234"

}

###
POST {{apiURL}}/auth/login
Content-Type: application/json

{
  "email": "tester@gmail.com", 
  "password": "1234"
}

###
POST {{apiURL}}/category
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlckBnbWFpbC5jb20iLCJpYXQiOjE3NjA1ODU0NzksImV4cCI6MTc2MDY3MTg3OX0.hn4nL4mUPC_44bnofSZn7-BqdMoDolHbt0jr-oaVZT4

{
  "name":"TVs"
}

###
 GET {{apiURL}}/category
Content-Type: application/json


#####
POST {{apiURL}}/products
Content-Type: application/json

{
  "name": "Nokia Lumia",
  "description": "Ancient Beast",
  "price": 300,
  "stock": 3,
  "category": "68c8f01555ede480a0121d5e",
  "images": ["https://msblogs.thesourcemediaassets.com/2013/08/5543.Lumia925Blk34Combo3ATT_5F00_LR_5F00_1CC4F241.jpg", "https://cdn.mos.cms.futurecdn.net/irLuBqtehijKJiyd8DWum8.jpg"],
  "speacility": "Doesnt break at all"
}


#####
GET {{apiURL}}/products



#####
#### Update product
PATCH {{apiURL}}/products
Content-Type: application/json

{
  "id": "68cfbe279b2684f7f1118e28", 
  "description": "Phone is now discontinued."
}


#####
#### Delete product
DELETE {{apiURL}}/products
Content-Type: application/json

{
  "id": "68cfbe279b2684f7f1118e28"
}


#####
#### get orders
GET {{apiURL}}/orders
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlckBnbWFpbC5jb20iLCJpYXQiOjE3NjA3NzA4NDgsImV4cCI6MTc2MTM3NTY0OH0.9JPajznin-OvOdLhAuysI7ivBomIWWjEMKb0Wqf2SKs


#### Update order status
PATCH {{apiURL}}/orders
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlckBnbWFpbC5jb20iLCJpYXQiOjE3NjA3NzA4NDgsImV4cCI6MTc2MTM3NTY0OH0.9JPajznin-OvOdLhAuysI7ivBomIWWjEMKb0Wqf2SKs

{
  "id": "68f33d4327e44ea4f38d7f20",
  "status": "Shipped"
}

### retrieve all the customer 
GET {{apiURL}}/customer
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlckBnbWFpbC5jb20iLCJpYXQiOjE3NjA5NTk0MDcsImV4cCI6MTc2MTA0NTgwN30.ruIEnLl8Wa5_H9kfXqt9LB7KNP8pmqzu1QH1SMLfL68

